# Model arguments
model_name_or_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_revision: main
torch_dtype: float32
use_flash_attention_2: false

# Data training arguments
dataset_mixer:
  - dataset: garage-bAInd/Open-Platypus
    proportion: 1.0
    dataset_splits:
    - train
    - test
    blacklist_sources:
    - scienceqa
    - reclor
    blacklist_sources_key: data_source
    converter:
      name: role_based_converter
      seperator: "\n\n"
  - dataset: teknium/GPTeacher-General-Instruct
    proportion: 1.0
    data_files: 
    - gpt4-instruct-dedupe-only-dataset.json
    converter:
      name: role_based_converter
      user_keys:
        - input
        - instruction
      assistant_keys:
        - response
      seperator: "\n\n"
  - dataset: teknium/openhermes
    proportion: 0.2
    converter:
      name: role_based_converter
      user_keys:
        - input
        - instruction
      assistant_keys:
        - output
      seperator: "\n\n"
  - dataset: Open-Orca/SlimOrca-Dedup
    proportion: 0.3
    converter:
      name: convert_to_hf_chat_template
  - dataset: databricks/databricks-dolly-15k
    proportion: 1
    converter:
      name: role_based_converter
      user_keys:
        - context
        - instruction
      assistant_keys:
        - response
      seperator: "\n\n"
preprocessing_num_workers: 12
truncation_side: right
use_fast_tokenizer: false

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 10
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: alexredna/TinyLlama-1.1B-Chat-v1.0-reasoning-v2
hub_strategy: every_save
learning_rate: 4.0e-05
log_level: info
logging_steps: 20  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 4
per_device_eval_batch_size: 2
per_device_train_batch_size: 4
push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: steps
save_steps: 40
save_total_limit: 5
seed: 42
tf32: false
resume_from_checkpoint: true
output_dir: data/TinyLlama-1.1B-Chat-v1.0-reasoning-v2
overwrite_output_dir: false

