# Model arguments
model_name_or_path: ./data/Tukan-1.1B-Chat_merged
model_revision: main
use_flash_attention_2: false
optimum: false

# LoRA arguments
load_in_4bit: true
load_in_8bit: false
use_peft: true
lora_r: 64
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
- lm_head

# Data training arguments
dataset_mixer:
  - dataset: garage-bAInd/Open-Platypus
    proportion: 0.20
    dataset_splits:
    - train
    - test
    blacklist_sources:
    - scienceqa
    - reclor
    blacklist_sources_key: data_source
    converter:
      name: role_based_converter
      seperator: "\n\n"
  - dataset: teknium/GPTeacher-General-Instruct
    proportion: 0.25
    data_files: 
    - gpt4-instruct-dedupe-only-dataset.json
    converter:
      name: role_based_converter
      user_keys:
        - input
        - instruction
      assistant_keys:
        - response
      seperator: "\n\n"
  - dataset: cognitivecomputations/dolphin-coder
    proportion: .07
    converter:
      name: role_based_converter
      system_keys:
        - system_prompt
      user_keys:
        - question
      assistant_keys:
        - response
      seperator: "\n\n"
  - dataset: teknium/openhermes
    proportion: 0.07
    converter:
      name: role_based_converter
      user_keys:
        - input
        - instruction
      assistant_keys:
        - output
      seperator: "\n\n"
  - dataset: Open-Orca/SlimOrca-Dedup
    proportion: .015
    converter:
      name: convert_to_hf_chat_template
preprocessing_num_workers: 12
truncation_side: right
use_fast_tokenizer: false

# SFT trainer config
optim: adamw_bnb_8bit
bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 10
gradient_accumulation_steps: 36
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
ddp_find_unused_parameters: false
hub_model_id: alexredna/Tukan-1.1B-Chat-v0.4
hub_strategy: every_save
learning_rate: 4.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
per_device_eval_batch_size: 3
per_device_train_batch_size: 5
push_to_hub: true # TODO reennable
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: steps
save_steps: 20
save_total_limit: 2
seed: 182
tf32: false
resume_from_checkpoint: false
output_dir: data/Tukan-1.1B-Chat
overwrite_output_dir: true
