# Model arguments
model_name_or_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_revision: main
use_flash_attention_2: false
optimum: false

# LoRA arguments
load_in_4bit: false
load_in_8bit: false
use_peft: true
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
- lm_head

# Data training arguments
dataset_mixer:
  - dataset: alexredna/slim_orca_hermes_reasoning_sft
    proportion: 1
  - dataset: alexredna/oasst2_dpo_pairs
    proportion: 1

preprocessing_num_workers: 12
truncation_side: right
use_fast_tokenizer: false

# SFT trainer config
optim: adamw_bnb_8bit
bf16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 10
gradient_accumulation_steps: 20
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
ddp_find_unused_parameters: false
hub_model_id: alexredna/Tukan-1.1B-Chat-reasoning-sft-COLA-2.5epr-R8-A16
hub_strategy: every_save
learning_rate: 5.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 5
per_device_eval_batch_size: 3
per_device_train_batch_size: 6
push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: steps
save_steps: 20
save_total_limit: 2
seed: 42
tf32: false
resume_from_checkpoint: false
output_dir: data/Tukan-1.1B-Chat-reasoning-sft-COLA-2.5epr-R8-A16
overwrite_output_dir: true

# Multi Lora training config
chain_of_lora_enabled: true
epochs_per_round: 2.5
resume_from_round: 0