# Model arguments
model_name_or_path: alexredna/TinyLlama-1.1B-Chat-v1.0-reasoning-v2
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  - dataset: Intel/orca_dpo_pairs 
    proportion: 1
    dataset_splits:
    - train
    - test
    converter:
      name: role_based_converter_dpo
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: alexredna/TinyLlama-1.1B-Chat-v1.0-reasoning-v2-dpo
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir: data/TinyLlama-1.1B-Chat-v1.0-reasoning-v2-dpo
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: true
report_to:
- tensorboard
- wandb
save_strategy: steps
save_steps: 150
save_total_limit: 2
seed: 42
warmup_ratio: 0.1